/** Friends a referrer needs before their page shows the Unlimited unlock. */
export const referralsNeeded = 3;

export const appSumoUrl = "https://appsumo.com/products/rhino/";
export const appSumoCoupon = "rhinofree";

/** Same code as /thanks; the app checks it against a SHA-256 hash in UsageGate.swift. */
export const unlockCode = "RHINO-33MY-Q56S";

/** Referral codes are generated by the app (ReferralLink.swift): 8 lowercase base32 chars. */
export function isReferralCode(code: string) {
  return /^[a-z2-7]{8}$/.test(code);
}

// worker/index.ts publishes the bindings here on every request. Not
// `cloudflare:workers`: the Node-run site tests can't import that module.
const db = () => {
  const binding = (globalThis as { __rhinoEnv?: { REFERRALS?: D1Database } }).__rhinoEnv?.REFERRALS;
  if (!binding) throw new Error("REFERRALS D1 binding is not configured");
  return binding;
};

let schemaReady: Promise<unknown> | undefined;
function ensureSchema() {
  schemaReady ??= db()
    .prepare(
      `CREATE TABLE IF NOT EXISTS referral_clicks (
         code TEXT NOT NULL,
         friend TEXT NOT NULL,
         destination TEXT NOT NULL,
         created_at INTEGER NOT NULL,
         PRIMARY KEY (code, friend)
       )`,
    )
    .run()
    .catch((error: unknown) => {
      schemaReady = undefined; // retry on the next request instead of caching the failure
      throw error;
    });
  return schemaReady;
}

async function sha256(value: string) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * One friend = one browser on one network: a hash of IP + user agent, salted with the
 * code. Nothing identifying is stored. Repeat clicks from the same friend count once.
 */
export async function recordReferralClick(code: string, request: Request, destination: string) {
  const ip = request.headers.get("cf-connecting-ip") ?? "";
  const ua = request.headers.get("user-agent") ?? "";
  const friend = await sha256(`${code}|${ip}|${ua}`);
  await ensureSchema();
  await db()
    .prepare(
      "INSERT OR IGNORE INTO referral_clicks (code, friend, destination, created_at) VALUES (?, ?, ?, ?)",
    )
    .bind(code, friend, destination, Date.now())
    .run();
}

export async function referralCount(code: string) {
  await ensureSchema();
  const row = await db()
    .prepare("SELECT COUNT(*) AS n FROM referral_clicks WHERE code = ?")
    .bind(code)
    .first<{ n: number }>();
  return row?.n ?? 0;
}
